### ISSUE TITLE
Test set

### ISSUE THREAD

**Issue by Ahmetf1** [adamshephard/TIAger#18]
First of all thank you for making this valuable work open-source.
Can you provide the information about from which dataset which samples you used for creating test set. So that we can compare the results of our model with yours ?

**Comment by adamshephard** [comment]
Hi,

Thanks for your email and I am pleased to hear that you are interested in our work.

The model was created as part of the TiGER challenge (Home - Grand Challenge (grand-challenge.org)<https://tiger.grand-challenge.org/>. The testing dataset has been withheld by the organisers and is not yet publicly available. I am not sure whether they are planning to release the data after the challenge paper has been published. However, I do believe that they may keep it online, and allow submissions to the leaderboards in the future.

Sorry I couldn’t be more help.

Best wishes,
Adam

Adam Shephard

Postdoctoral Research Fellow
Department of Computer Science
University of Warwick
West Midlands, UK

From: Ahmet Furkan Akıncı ***@***.***>
Sent: 25 February 2023 19:47
To: adamshephard/TIAger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adamshephard/TIAger] Test set (Issue #18)


First of all thank you for making this valuable work open-source.
Can you provide the information about from which dataset which samples you used for creating test set. So that we can compare the results of our model with yours ?

**Comment by Ahmetf1** [comment]
Thanks anyway.
